### ISSUE TITLE
Add links to preprocess documentation in root README.

### ISSUE THREAD

**Issue by umesh-timalsina** [KyleAMoore/Redshift-ResNet#22]
It might be helpful to add links to preprocessing README.md file at the root README of the Repository.

**Comment by KyleAMoore** [comment]
I've added links to all READMEs and noteworthy scripts of which I am aware in the form of a project map (using a directory tree structure). I am leaving this issue open for now in case the map needs to be replaced with a better link representation or in case additional links need to be added to it from the preprocessing directory.

**Comment by KyleAMoore** [comment]
As there have been no recommended or requested changes to this in over a week, I am closing this issue. Any future required changes can be included as a step in documenting future features.
